### ISSUE TITLE
Move the plugin to serverless-heaven and set up a maintainer team

### ISSUE THREAD

**Issue by rdsedmundo** [serverless-heaven/serverless-aws-alias#154]
Hello @HyperBrain.

I noticed as per your GitHub contribution chart that you are not too much active since the end of H1/2018. My company relies on your `serverless-*` plugins, namely this `alias` one and the `webpack`, and we'd like to know what is the plan with those repositories. Are you planning to come back and address the issues here? Are you seeking for contributions? Or should we consider this repository archived?

Thank you in advance.

**Comment by Enase** [comment]
+1, do you need any help? or it is the end...

**Comment by HyperBrain** [comment]
Hi @rdsedmundo , @Enase ,

I'm currently recovering work on `serverless-webpack` and release fixes for that project in the near future (5.3.0 is finalizing right now). Although I managed to have more time again for the projects, I currently cannot maintain both with full efforts, but only one in the quality they deserve. For webpack I can guarantee now, that it will be up again.

So, I appreciate your offer for help for `serverless-aws-alias`. In my opinion, it would be the best to move it to `serverless-heaven` too, because I have more options to create specific user groups and rights there.
If you agree I would do that and invite you to the appropriate group with write access then.

Regarding NPM releases, I can do them on request.

Comments welcome!

**Comment by Enase** [comment]
@HyperBrain sure, let's do it. I'm ready to help as I said.

**Comment by aleksdikanski** [comment]
@HyperBrain @Enase I also have an interest in this plugin and would like to contribute.

**Comment by MartinRisk** [comment]
@HyperBrain  I am using this plugin for our projects and would also like to contibute

**Comment by HyperBrain** [comment]
Just changing the title of the issue to reflect the upcoming changes.
I'm currently setting up a dedicated maintainer team at my GitHub organization `serverless-heaven`.

**Comment by HyperBrain** [comment]
The project has been moved!

**Comment by Enase** [comment]
Thanks, I'll start in a few days. BTW is there any way to communicate? any slack channel or something..

**Comment by nathanchapman** [comment]
I work with @rdsedmundo. I'd be happy to assist as well 👍

**Comment by HyperBrain** [comment]
Hey Nathan, I'll add you to the team too ;-)

Regarding the communication, we can use the team discussion
board serverless-heaven in the team view (teams ->
serverless-aws-alias-team). I already posted 2 items there.

**Comment by nathanchapman** [comment]
Hey @HyperBrain! No luck seeing the team discussion board yet. Mind double checking I'm on there when you get a chance?

**Comment by HyperBrain** [comment]
Will check until tomorrow :-)

**Comment by HyperBrain** [comment]
@nathanchapman Sorry, I indeed forgot to add you to the team 😄 . Invite on its way.

**Comment by HyperBrain** [comment]
@serverless-heaven/serverless-aws-alias-team I'm just releasing `1.7.2`. Should be done in a few minutes.

**Comment by HyperBrain** [comment]
BTW: I think we now have a working team here 😄 . Feel free to close this issue if you agree.
